#! /usr/bin/zsh

#xcompmgr &

# Randomly change wallpaper in root window with feh
  3 
  4 # Directories to search for images
  5 # (errors from nonexistent directories will be ignored)
  6 SRC="/media/sdc1/random/wallpaper/Wallpapers/"
  7 
  8 while true; do
  9     feh -qrz --bg-scale $(echo "${SRC}") 2> /dev/null
 10     sleep 3m
 11 done

