#! /bin/bash

xinput set-prop 10 "Device Accel Profile" -1
xinput set-prop 10 "Device Accel Constant Deceleration" 1.0
xinput set-float-prop 10 "Device Accel Apaptive Deceleration" 1
xinput set-prop 10 "Device Accel Velocity Scaling" 1
