#! /bin/bash

xinput set-prop "Logitech G400s Optical Gaming Mouse" "Device Accel Profile" -1 # -1 to disable mouse acceleration
xinput set-prop "Logitech G400s Optical Gaming Mouse" "Device Accel Constant Deceleration" 1.96 # Higher value slows mouse speed, default 1.00
xinput set-float-prop "Logitech G400s Optical Gaming Mouse" "Device Accel Apaptive Deceleration" 1 
xinput set-prop "Logitech G400s Optical Gaming Mouse" "Device Accel Velocity Scaling" 1
