#!/usr/bin/zsh

#tty-clock urxvt asetuksilla
# -s			show seconds
# -c			Set clock at the center of terminal
# -C[0-7]		Set clock font color
# -b			Use bold colors
# -f 			set date format [eg.dd/mm/yy %A-%B-%d]
# -D 			Hide date
# -B			Enable blinking colon
# -d delay		Set delay between two redraws of the clock. Default 1s
# -a nsdelay		Delay in nanoseconds. Default 0ns


export LANG=fi_FI.UTF-8

sleep 5 &
urxvt -borderLess -geometry 54x10+2800+50 -depth 32 -bg rgba:3f00/3f00/3f00/8111 -e tty-clock -s  -f %A-%B-%d 

